import '../models/achievement.dart';
import '../models/mission.dart';

class AchievementCatalog {
  static const List<Achievement> all = [
    Achievement(
      id: 'first_mission',
      title: 'First Steps',
      emoji: '🌱',
      description: 'Selesaikan misi pertama kamu.',
      metric: AchievementMetric.totalMissions,
      target: 1,
    ),
    Achievement(
      id: 'ten_missions',
      title: 'Getting the Hang of It',
      emoji: '🎯',
      description: 'Selesaikan 10 misi.',
      metric: AchievementMetric.totalMissions,
      target: 10,
    ),
    Achievement(
      id: 'fifty_missions',
      title: 'Boredom Veteran',
      emoji: '🏆',
      description: 'Selesaikan 50 misi.',
      metric: AchievementMetric.totalMissions,
      target: 50,
    ),
    Achievement(
      id: 'streak_3',
      title: 'On a Roll',
      emoji: '🔥',
      description: 'Capai streak 3 hari berturut-turut.',
      metric: AchievementMetric.streak,
      target: 3,
    ),
    Achievement(
      id: 'streak_7',
      title: 'Week Warrior',
      emoji: '📅',
      description: 'Capai streak 7 hari berturut-turut.',
      metric: AchievementMetric.streak,
      target: 7,
    ),
    Achievement(
      id: 'streak_30',
      title: 'Unstoppable',
      emoji: '🚀',
      description: 'Capai streak 30 hari berturut-turut.',
      metric: AchievementMetric.streak,
      target: 30,
    ),
    Achievement(
      id: 'level_10',
      title: 'Touching Grass',
      emoji: '🌿',
      description: 'Capai level 10.',
      metric: AchievementMetric.level,
      target: 10,
    ),
    Achievement(
      id: 'level_20',
      title: 'Main Character',
      emoji: '🌟',
      description: 'Capai level 20.',
      metric: AchievementMetric.level,
      target: 20,
    ),
    Achievement(
      id: 'level_50',
      title: 'Chronically Unbored',
      emoji: '👑',
      description: 'Capai level 50.',
      metric: AchievementMetric.level,
      target: 50,
    ),
    Achievement(
      id: 'chaos_5',
      title: 'Chaos Enjoyer',
      emoji: '☢️',
      description: 'Selesaikan 5 misi lewat Chaos Mode.',
      metric: AchievementMetric.chaosMissions,
      target: 5,
    ),
    Achievement(
      id: 'reroll_10',
      title: 'Reroll Addict',
      emoji: '💀',
      description: 'Reroll misi sebanyak 10 kali (total).',
      metric: AchievementMetric.rerollsAllTime,
      target: 10,
    ),
    Achievement(
      id: 'app_opens_7',
      title: 'Bro Has Nothing To Do',
      emoji: '🗿',
      description: 'Buka aplikasi 7 kali dalam satu hari.',
      metric: AchievementMetric.appOpensSingleDay,
      target: 7,
    ),
    Achievement(
      id: 'quest_master',
      title: 'Quest Master',
      emoji: '🧩',
      description: 'Selesaikan satu Quest Chain sampai tuntas.',
      metric: AchievementMetric.questChainsCompleted,
      target: 1,
    ),
    Achievement(
      id: 'night_owl',
      title: 'Night Owl',
      emoji: '🌙',
      description: 'Selesaikan misi setelah jam 11 malam.',
      metric: AchievementMetric.special,
      target: 1,
    ),
    Achievement(
      id: 'cat_outdoor',
      title: 'Touch Grass Certified',
      emoji: '🌳',
      description: 'Selesaikan 5 misi kategori Outdoor.',
      metric: AchievementMetric.categoryCount,
      target: 5,
      category: MissionCategory.outdoor,
    ),
    Achievement(
      id: 'cat_photography',
      title: 'Photographer',
      emoji: '📸',
      description: 'Selesaikan 10 misi kategori Photography.',
      metric: AchievementMetric.categoryCount,
      target: 10,
      category: MissionCategory.photography,
    ),
    Achievement(
      id: 'cat_coding',
      title: 'Certified Nerd',
      emoji: '⌨️',
      description: 'Selesaikan 5 misi kategori Coding.',
      metric: AchievementMetric.categoryCount,
      target: 5,
      category: MissionCategory.coding,
    ),
    Achievement(
      id: 'cat_social',
      title: 'Socialite',
      emoji: '💬',
      description: 'Selesaikan 5 misi kategori Social.',
      metric: AchievementMetric.categoryCount,
      target: 5,
      category: MissionCategory.social,
    ),
    Achievement(
      id: 'cat_creative',
      title: 'Creative Soul',
      emoji: '🎨',
      description: 'Selesaikan 5 misi kategori Creative.',
      metric: AchievementMetric.categoryCount,
      target: 5,
      category: MissionCategory.creative,
    ),
    Achievement(
      id: 'cat_learning',
      title: 'Brainiac',
      emoji: '🧠',
      description: 'Selesaikan 5 misi kategori Learning.',
      metric: AchievementMetric.categoryCount,
      target: 5,
      category: MissionCategory.learning,
    ),
    Achievement(
      id: 'cat_self',
      title: 'Self-Care Champion',
      emoji: '✨',
      description: 'Selesaikan 5 misi kategori Self-Improvement.',
      metric: AchievementMetric.categoryCount,
      target: 5,
      category: MissionCategory.selfImprovement,
    ),
  ];

  /// orElse fallback ke entri pertama - jaga-jaga kalau suatu saat ada
  /// achievement lama yang dihapus/rename dari katalog tapi id-nya masih
  /// kesimpen di progress user, biar app nggak crash pas render.
  static Achievement byId(String id) =>
      all.firstWhere((a) => a.id == id, orElse: () => all.first);
}
