import '../models/mission.dart';

/// Katalog statis semua misi yang bisa keluar di Boredom.
/// Tambah/edit misi di sini aja, generator otomatis ambil dari sini.
class MissionCatalog {
  static const List<Mission> all = [
    // ---------------- HOME / LAZY ----------------
    Mission(
      id: 'home_01',
      title: 'Room Archaeologist',
      emoji: '🗄️',
      description:
          'Bersihin satu sudut kamar yang paling berantakan. Cuma satu sudut, bukan sekamar.',
      category: MissionCategory.selfImprovement,
      difficulty: 2,
      baseXp: 30,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.lazy, Mood.normal},
      locations: {LocationType.home},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'home_02',
      title: 'Playlist Time Capsule',
      emoji: '🎧',
      description: 'Dengerin ulang playlist atau album lama yang udah lama nggak kamu putar.',
      category: MissionCategory.entertainment,
      difficulty: 1,
      baseXp: 15,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.lazy, Mood.bored, Mood.normal},
      locations: {LocationType.home, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'home_03',
      title: 'Stretch Break',
      emoji: '🧘',
      description: 'Stretching ringan 5 menit. Fokus ke leher, pundak, sama punggung.',
      category: MissionCategory.selfImprovement,
      difficulty: 1,
      baseXp: 15,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.lazy, Mood.normal, Mood.energetic},
      locations: {LocationType.home, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'home_04',
      title: 'Fridge Roulette',
      emoji: '🍳',
      description: 'Bikin makanan/minuman dari 3 bahan random yang ada di kulkas/dapur.',
      category: MissionCategory.creative,
      difficulty: 2,
      baseXp: 35,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.normal, Mood.curious},
      locations: {LocationType.home},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'home_05',
      title: 'Digital Declutter',
      emoji: '🗑️',
      description: 'Hapus 20 foto/screenshot nggak penting dari galeri.',
      category: MissionCategory.selfImprovement,
      difficulty: 1,
      baseXp: 20,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.lazy, Mood.bored, Mood.normal},
      locations: {LocationType.home, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),

    // ---------------- GAMING ----------------
    Mission(
      id: 'game_01',
      title: 'Backlog Raid',
      emoji: '🎮',
      description: 'Mainin game di library kamu yang belum pernah/jarang disentuh, minimal 20 menit.',
      category: MissionCategory.gaming,
      difficulty: 1,
      baseXp: 25,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.bored, Mood.normal, Mood.energetic},
      locations: {LocationType.home, LocationType.computer},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'game_02',
      title: 'Hardcore Mode',
      emoji: '💀',
      description: 'Coba clear satu level/misi di difficulty tertinggi yang biasanya kamu hindari.',
      category: MissionCategory.gaming,
      difficulty: 4,
      baseXp: 60,
      maxTime: TimeBudget.oneHour,
      moods: {Mood.energetic},
      locations: {LocationType.home, LocationType.computer},
      energyLevels: {EnergyLevel.high},
    ),
    Mission(
      id: 'game_03',
      title: 'Mobile Quickie',
      emoji: '📱',
      description: 'Mainin satu game mobile ringan sampe dapet 1 pencapaian/level up.',
      category: MissionCategory.gaming,
      difficulty: 1,
      baseXp: 15,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.lazy, Mood.bored},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),

    // ---------------- CODING ----------------
    Mission(
      id: 'code_01',
      title: '30-Minute Ship',
      emoji: '🛠️',
      description: 'Bikin script/tool kecil yang nyelesain satu masalah receh kamu sendiri.',
      category: MissionCategory.coding,
      difficulty: 3,
      baseXp: 50,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.curious, Mood.energetic},
      locations: {LocationType.computer},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'code_02',
      title: 'Bug Bounty (Personal Edition)',
      emoji: '🐛',
      description: 'Buka salah satu project lama kamu, cari & fix satu bug atau TODO yang ketunda.',
      category: MissionCategory.coding,
      difficulty: 3,
      baseXp: 45,
      maxTime: TimeBudget.oneHour,
      moods: {Mood.normal, Mood.curious},
      locations: {LocationType.computer},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'code_03',
      title: 'README Glow Up',
      emoji: '📝',
      description: 'Rapihin README atau dokumentasi salah satu repo GitHub kamu.',
      category: MissionCategory.coding,
      difficulty: 2,
      baseXp: 30,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.normal, Mood.lazy},
      locations: {LocationType.computer},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'code_04',
      title: 'Learn One Weird Trick',
      emoji: '⌨️',
      description: 'Cari & coba satu fitur bahasa pemrograman/library yang belum pernah kamu pakai.',
      category: MissionCategory.coding,
      difficulty: 2,
      baseXp: 35,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.curious},
      locations: {LocationType.computer},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),

    // ---------------- LEARNING ----------------
    Mission(
      id: 'learn_01',
      title: 'Wikipedia Rabbit Hole',
      emoji: '🐇',
      description: 'Buka Wikipedia, mulai dari topik random, ikutin link sampe 5 halaman.',
      category: MissionCategory.learning,
      difficulty: 1,
      baseXp: 20,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.curious, Mood.bored},
      locations: {LocationType.anywhere, LocationType.computer},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'learn_02',
      title: 'Word of the Day',
      emoji: '📖',
      description: 'Pelajari 3 kosakata baru dalam bahasa asing yang pengen kamu kuasain.',
      category: MissionCategory.learning,
      difficulty: 1,
      baseXp: 20,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.curious, Mood.normal},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'learn_03',
      title: 'Documentary Deep Dive',
      emoji: '🎥',
      description: 'Tonton satu video/dokumenter edukatif tentang topik yang belum kamu ngerti.',
      category: MissionCategory.learning,
      difficulty: 2,
      baseXp: 35,
      maxTime: TimeBudget.oneHour,
      moods: {Mood.curious, Mood.normal},
      locations: {LocationType.home, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),

    // ---------------- CREATIVE ----------------
    Mission(
      id: 'creative_01',
      title: 'Napkin Sketch',
      emoji: '✏️',
      description: 'Gambar apa aja yang ada di sekitar kamu, 10 menit, nggak usah bagus.',
      category: MissionCategory.creative,
      difficulty: 1,
      baseXp: 20,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.bored, Mood.curious, Mood.normal},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'creative_02',
      title: 'One-Line Story',
      emoji: '✒️',
      description: 'Tulis cerita super pendek (1-3 kalimat) dari kejadian random hari ini.',
      category: MissionCategory.creative,
      difficulty: 1,
      baseXp: 15,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.curious, Mood.normal},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'creative_03',
      title: 'Playlist Curator',
      emoji: '🎵',
      description: 'Bikin playlist baru dengan tema random (misal: "lagu buat ngoding jam 2 pagi").',
      category: MissionCategory.creative,
      difficulty: 2,
      baseXp: 25,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.normal, Mood.curious},
      locations: {LocationType.anywhere, LocationType.computer},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),

    // ---------------- PHOTOGRAPHY ----------------
    Mission(
      id: 'photo_01',
      title: 'Photo Hunter',
      emoji: '📸',
      description: 'Keluar sebentar dan cari 3 benda berwarna merah, foto semuanya.',
      category: MissionCategory.photography,
      difficulty: 2,
      baseXp: 40,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.normal, Mood.energetic, Mood.curious},
      locations: {LocationType.outside},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'photo_02',
      title: 'Macro Hunter',
      emoji: '🔍',
      description: 'Foto satu benda kecil di rumah kamu dari jarak sedeket mungkin.',
      category: MissionCategory.photography,
      difficulty: 1,
      baseXp: 15,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.bored, Mood.curious},
      locations: {LocationType.home},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'photo_03',
      title: 'Golden Hour Chase',
      emoji: '🌇',
      description: 'Ambil satu foto langit/matahari terbenam terbaik yang kamu bisa.',
      category: MissionCategory.photography,
      difficulty: 2,
      baseXp: 30,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.normal, Mood.curious},
      locations: {LocationType.outside},
      energyLevels: {EnergyLevel.medium},
    ),

    // ---------------- OUTDOOR ----------------
    Mission(
      id: 'outdoor_01',
      title: 'Ten-Minute Wander',
      emoji: '🚶',
      description: 'Jalan kaki keluar rumah 10 menit, tanpa tujuan spesifik.',
      category: MissionCategory.outdoor,
      difficulty: 1,
      baseXp: 25,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.bored, Mood.normal, Mood.lazy},
      locations: {LocationType.outside},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'outdoor_02',
      title: 'Uncharted Territory',
      emoji: '🗺️',
      description: 'Pergi ke satu tempat di sekitar rumah kamu yang belum pernah kamu datangi.',
      category: MissionCategory.outdoor,
      difficulty: 3,
      baseXp: 50,
      maxTime: TimeBudget.oneHour,
      moods: {Mood.curious, Mood.energetic},
      locations: {LocationType.outside},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'outdoor_03',
      title: 'Warung Run',
      emoji: '🏪',
      description: 'Jalan ke warung/minimarket terdekat, beli sesuatu yang belum pernah kamu coba.',
      category: MissionCategory.outdoor,
      difficulty: 2,
      baseXp: 30,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.bored, Mood.normal, Mood.curious},
      locations: {LocationType.outside},
      energyLevels: {EnergyLevel.medium},
    ),
    Mission(
      id: 'outdoor_04',
      title: 'No-Phone Sit',
      emoji: '🌳',
      description: 'Duduk di luar selama 10 menit tanpa buka HP sama sekali.',
      category: MissionCategory.outdoor,
      difficulty: 3,
      baseXp: 40,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.normal, Mood.energetic},
      locations: {LocationType.outside},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),

    // ---------------- SOCIAL ----------------
    Mission(
      id: 'social_01',
      title: 'Ghost Reactivation',
      emoji: '👻',
      description: 'Chat/telepon teman lama yang udah lama nggak kamu hubungin.',
      category: MissionCategory.social,
      difficulty: 3,
      baseXp: 45,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.normal, Mood.energetic},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'social_02',
      title: 'Compliment Bomb',
      emoji: '💬',
      description: 'Kirim satu pesan random buat bikin hari orang lain lebih baik.',
      category: MissionCategory.social,
      difficulty: 1,
      baseXp: 20,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.normal, Mood.energetic, Mood.curious},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'social_03',
      title: 'Group Chat Reviver',
      emoji: '📣',
      description: 'Kirim sesuatu yang lucu/menarik ke grup chat yang lagi sepi.',
      category: MissionCategory.social,
      difficulty: 1,
      baseXp: 15,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.bored, Mood.normal},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),

    // ---------------- SELF-IMPROVEMENT ----------------
    Mission(
      id: 'self_01',
      title: 'Future You Letter',
      emoji: '✉️',
      description: 'Tulis catatan singkat buat diri kamu 1 tahun dari sekarang.',
      category: MissionCategory.selfImprovement,
      difficulty: 2,
      baseXp: 30,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.curious, Mood.normal},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'self_02',
      title: 'Money Check',
      emoji: '💸',
      description: 'Cek pengeluaran 3 hari terakhir, catat satu hal yang bisa dihemat.',
      category: MissionCategory.selfImprovement,
      difficulty: 2,
      baseXp: 25,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.normal},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.medium},
    ),
    Mission(
      id: 'self_03',
      title: '25-Minute Focus',
      emoji: '⏱️',
      description: 'Pomodoro 25 menit buat ngerjain satu tugas yang selama ini ditunda.',
      category: MissionCategory.selfImprovement,
      difficulty: 3,
      baseXp: 45,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.normal, Mood.energetic},
      locations: {LocationType.home, LocationType.computer},
      energyLevels: {EnergyLevel.medium, EnergyLevel.high},
    ),
    Mission(
      id: 'self_04',
      title: 'Inbox Zero (Sort Of)',
      emoji: '📥',
      description: 'Beresin 10 notifikasi/email yang numpuk.',
      category: MissionCategory.selfImprovement,
      difficulty: 1,
      baseXp: 20,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.lazy, Mood.normal},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),

    // ---------------- ENTERTAINMENT ----------------
    Mission(
      id: 'ent_01',
      title: 'Genre Roulette',
      emoji: '🎬',
      description: 'Tonton trailer/episode pertama dari genre film/series yang jarang kamu tonton.',
      category: MissionCategory.entertainment,
      difficulty: 1,
      baseXp: 20,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.lazy, Mood.bored, Mood.curious},
      locations: {LocationType.home, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium},
    ),
    Mission(
      id: 'ent_02',
      title: 'Meme Archaeologist',
      emoji: '😂',
      description: 'Cari 5 meme lama yang bikin kamu ketawa, share ke satu orang.',
      category: MissionCategory.entertainment,
      difficulty: 1,
      baseXp: 15,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.lazy, Mood.bored},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low},
    ),

    // ---------------- CHAOS-ONLY ----------------
    Mission(
      id: 'chaos_01',
      title: 'Pin The Map',
      emoji: '☢️',
      description:
          'Buka Maps, pilih titik random dalam radius 5km, coba cari cara buat ke sana (nggak harus beneran pergi).',
      category: MissionCategory.chaos,
      difficulty: 4,
      baseXp: 70,
      maxTime: TimeBudget.oneHour,
      moods: {Mood.lazy, Mood.bored, Mood.normal, Mood.energetic, Mood.curious},
      locations: {LocationType.home, LocationType.outside, LocationType.computer, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium, EnergyLevel.high},
      chaosOnly: true,
    ),
    Mission(
      id: 'chaos_02',
      title: 'Cook Blindfolded',
      emoji: '🎰',
      description: 'Tutup mata, tunjuk random 3 bumbu/bahan di dapur, wajib dipakai bertiga dalam satu masakan.',
      category: MissionCategory.chaos,
      difficulty: 3,
      baseXp: 55,
      maxTime: TimeBudget.thirtyMin,
      moods: {Mood.lazy, Mood.bored, Mood.normal, Mood.energetic, Mood.curious},
      locations: {LocationType.home},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium, EnergyLevel.high},
      chaosOnly: true,
    ),
    Mission(
      id: 'chaos_03',
      title: 'DM a Stranger (Nicely)',
      emoji: '🎲',
      description: 'Komen positif dan jujur di postingan seseorang yang nggak kamu kenal, tanpa alasan jelas.',
      category: MissionCategory.chaos,
      difficulty: 3,
      baseXp: 50,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.lazy, Mood.bored, Mood.normal, Mood.energetic, Mood.curious},
      locations: {LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium, EnergyLevel.high},
      chaosOnly: true,
    ),
    Mission(
      id: 'chaos_04',
      title: 'Reverse Schedule',
      emoji: '🔄',
      description: 'Lakuin kebalikan dari kebiasaan kamu sekarang: kalau biasa rebahan, berdiri. Kalau biasa diem, gerak.',
      category: MissionCategory.chaos,
      difficulty: 2,
      baseXp: 35,
      maxTime: TimeBudget.fiveMin,
      moods: {Mood.lazy, Mood.bored, Mood.normal, Mood.energetic, Mood.curious},
      locations: {LocationType.home, LocationType.outside, LocationType.computer, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium, EnergyLevel.high},
      chaosOnly: true,
    ),
    Mission(
      id: 'chaos_05',
      title: 'Alphabet Challenge',
      emoji: '🔤',
      description: 'Sebutin/tulis satu benda di sekitar kamu buat tiap huruf A sampai J.',
      category: MissionCategory.chaos,
      difficulty: 2,
      baseXp: 30,
      maxTime: TimeBudget.fifteenMin,
      moods: {Mood.lazy, Mood.bored, Mood.normal, Mood.energetic, Mood.curious},
      locations: {LocationType.home, LocationType.outside, LocationType.computer, LocationType.anywhere},
      energyLevels: {EnergyLevel.low, EnergyLevel.medium, EnergyLevel.high},
      chaosOnly: true,
    ),
  ];
}
